### ISSUE TITLE
How to compile without running?

### ISSUE THREAD

**Issue by JohanWinther** [joakin/elm-node#4]
Hello :wave:

I'd like to know if it's possible to compile the files in `elm-node-stuff` (`elm.js`, `index.js` and `user.js`) without running the app.

**Context:**
We want to

1. Build the app
2. In the dockerfile, copy `elm-node-stuff` files into the workdir
3. In the dockerfile, run the app with node

**Comment by joakin** [comment]
Not at this time,
https://github.com/joakin/elm-node/blob/97dfedff73d9082a0379cce5851f6b05caeeb0ad/index.js#L86

The index file is required after compiling.

I’m not really using this package any more, feel free to fork and add a new
parameter to only compile, or  even just remove that require line 😄

**Comment by JohanWinther** [comment]
Thanks for the suggestion, but we opted to instead remove this dependency and compile with Elm only!

**Comment by joakin** [comment]
Great idea! 👍
